# Generated by Django 4.2.4 on 2023-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usarios',
            fields=[
                ('pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.FloatField(max_length=255)),
                ('endereço', models.TextField(max_length=255)),
                ('combo', models.TextField(max_length=255)),
            ],
        ),
    ]
