# Generated by Django 4.2.4 on 2023-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.TextField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('combo', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usarios',
        ),
    ]
