# Generated by Django 4.2.4 on 2023-09-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='combo',
            field=models.CharField(max_length=255),
        ),
    ]
