# Generated by Django 4.2.4 on 2023-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_alter_usuario_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='combo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
